### ISSUE TITLE
Benchmark Results and new GH Comments

### ISSUE THREAD

**Issue by juanpedromoreno** [47degrees/sbt-hood#147]
Currently, using the latest version ([v0.3.0](https://github.com/47degrees/sbt-hood/releases/tag/v0.3.0)), given an opened PR, every time that one commit is run on CI, adds a **new** comment. Would it make sense to update the existing one?

Example: https://github.com/47degrees/memeid/pull/195

**Comment by fedefernandez** [comment]
Yeah, the requirements initially said to update in case it exists so potentially this is a bug. thanks
